name: joomla

services:

    www:
        container_name: Joomla4

        image: joomla
        depends_on:
            sql:
                condition: service_healthy

        networks:
            - joomla
        ports:
            - "80:80"
            - "443:443"

        volumes:
            - joomla:/var/www/html
            - apache:/etc/apache2
            - phpini:/usr/local/etc/php

        env_file: stack.env

        healthcheck:
            test: ["CMD", "curl", "--head", "--fail", "http://localhost"]
            start_period: 30s
            interval: 1m
            timeout: 20s
            retries: 3
        
        restart: always

    sql:
        container_name: MariaDB

        image: mariadb

        networks:
            - joomla
        expose:
            - "3306"

        volumes:
            - mariadb:/var/lib/mysql
        
        env_file: stack.env

        healthcheck:
            test: ["CMD", "mariadb-admin", "--user=root", "--password=${MARIADB_ROOT_PASSWORD}", "ping"]
            start_period: 30s
            interval: 1m
            timeout: 10s
            retries: 3

        restart: always

    adm:
        container_name: MyAdmin

        image: phpmyadmin
        depends_on:
            - sql

        networks:
            - joomla
        ports:
            - "8080:80"

        profiles:
            - admin
            - debug

        env_file: stack.env

        restart: always

networks:

    joomla:
        name: Joomla
        driver: bridge


volumes:

    joomla:
        name: Joomla4

    mariadb:
        name: MariaDB

    myadmin:
        name: MyAdmin

    apache:
        name: Apache2

    phpini:
        name: PHP.ini
